#!/bin/sh
set -eu

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

xcrun safari-web-extension-converter "$repo_dir/dist/extension" \
  --project-location "$repo_dir/safari" \
  --app-name "Grocery Price Per Unit" \
  --bundle-identifier "ca.grocerypriceperunit" \
  --swift --copy-resources --no-open --no-prompt --force

# The converter inserts the local macOS account name into generated Swift
# headers. Keep generated source deterministic and safe to publish.
find "$repo_dir/safari/Grocery Price Per Unit" -type f -name '*.swift' \
  -exec sed -i '' -E 's|^//  Created by .* on [0-9-]+\.$|//  Generated by safari-web-extension-converter.|' {} +
